server:
  port: 9002

# 服务监控暴露端口
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: alibaba-provider
  cloud:
    nacos:
      discovery:
        # nacos注册地址
        server-addr: 1.116.128.254:8848
        username: nacos
        password: nacos