# 端口
server:
  port: 9527

# eureka服务
eureka:
  client:
    # true标识注册中心注册自己
    register-with-eureka: true
    # true标识自己就是客户端，需要检索服务
    fetch-registry: true
    # 设置与eureka server交互的地址查询服务和注册服务都需要这个地址
    service-url:
      defaultZone: http://localhost:8080/eureka
  # 简略名称
  instance:
    instance-id: gateway9527
    # 访问地址可以显示ip地址
    prefer-ip-address: true
    # eureka在收到最后一次心跳检验之后等待的时间上限(默认时90s)
    lease-expiration-duration-in-seconds: 90
    # eureka客户端向服务端发送心跳的时间间隔(默认30s)
    lease-renewal-interval-in-seconds: 30

# spring配置
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        # 路由的Id，要求唯一
        - id: payment_routh
          # 匹配后提供的服务地址
          uri: lb://cloud-payment
          # 断言，路由相匹配的进行路由
          predicates:
            - Path=/test/**